server:
  port: 8104
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: