server:
  port: 8101
  servlet:
    context-path: /api/v1

  datasource:
    url: jdbc:h2:tcp://localhost:9091/mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: none